language: node_js
node_js: stable
script:
  - bash ./gpages_build.sh <%= github %> <%= elementName %> <%= authorName %> <%= authorEmail %>
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH